### PR TITLE
Fix compilation with grbl v1.1f on linux using GCC 11.1.0

### PR DESCRIPTION
**Pull request by hrobeers**
I needed these changes to make grbl-sim compile on linux using GCC 11.1.0 against grbl v1.1f

These were all issues of multiple definitions in the linking stage.

### CODE REVIEW

**Comment by flynneva** [comment]
@hrobeers can confirm this MR does fix the compilation issues I was seeing as well 👍🏼  thanks!

**Comment by Leandro-Bertoluzzi** [comment]
It also helped me compiling it in Windows, thanks!

**Comment by stb1Cluny** [comment]
This helped me too, thanks!

built with: gcc (Debian 12.2.0-14) 12.2.0
uname -v: #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25)
Raspberry Pi 4b running Raspbian Bookworm
